apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pong-app
  template:
    metadata:
      labels:
        app: pong-app
    spec:
      containers:
        - name: Pong-app container
          image: criszzamora/dev-ops_personal:latest  # Docker Hub image reference
          ports:
            - containerPort: 3000